# Define version for Docker Compose
version: '3.8'

# Services
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
      volumes:
        - ./index.html:/usr/share/nginx/html/index.html
      restart: always

  db:
    img: mysql:8.0
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mydatabase
        volumes:
          - db_data:/var/lib/mysql
        restart: unless_stopped

  volumes:
    - db_data:
